### ISSUE TITLE
error while exporting the table

### ISSUE THREAD

**Issue by bioinfo-gv** [simonw/airtable-export#17]
Hi,

I am trying to export few of our airtables and i end up with client 401 and 406 errors. can you please let me know whats going wrong. I have key listed in the environment variable (.bash_profile)

 airtable-export $PWD appxxxxxxx Table1 --key=key --ndjson

Error: 406 Client Error: Not Acceptable for url: https://api.airtable.com/v0/appxxxxxx/Table1
For more information check: https://httpstatuses.com/406

Thanks,

**Comment by kbsali** [comment]
It looks like you are having the same issue I was having when starting using this script.
You need to specify a user-agent eg `--user-agent="tenseg/0.6"`
See #15
