### ISSUE TITLE
Airtable is changing its authentication system

### ISSUE THREAD

**Issue by wkdewey** [simonw/airtable-export#21]
See this announcement: https://community.airtable.com/t5/announcements/new-api-capabilities-now-in-ga-and-upcoming-api-keys-deprecation/ba-p/141824?utm_ID=recdXE5vJZZ5vR0mh&utm_ID=recdXE5vJZZ5vR0mh&utm_source=lifecycle_team&utm_source=lifecycle_team&utm_medium=email&utm_medium=email&utm_campaign=it_ss_ss_api_deprecation&utm_campaign=it_ss_ss_api_depreciation&utm_content=email-blast_api_1a&utm_content=email-blast_api_key_users. Will this tool still work with the new system?

**Comment by curt-mitch** [comment]
I was able to test this successfully by passing a new personal access token as the `--key=key` parameter. 

It looks like the way this tool is passing the key as a bearer token is still in line with what the new personal access token is expecting for Airtable's API: https://github.com/simonw/airtable-export/blob/fdb3decfaf844c8ce518aa0206bff9c17d019e13/airtable_export/cli.py#L113

See the Example block of code here: https://airtable.com/developers/web/api/authentication

**Comment by pmareke** [comment]
Hi @wkdewey and @curt-mitch Exactly, from the point of view of the user of the Airtable API is as simple as passing an access token instead of an API Key.

**Comment by simonw** [comment]
Glad to hear personal access tokens still work!
